# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RNFirebaseStarter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNFirebaseStarter

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.9.0'

  target 'RNFirebaseStarterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end